Edit calendar items
ProjectMaasgroep18/ms18-flutter-applicatie pull request #21
Opened 2023-12-04 13:33 UTC by Vinciepincie

Op basis van add calendar items
https://github.com/ProjectMaasgroep18/ms18-flutter-applicatie/pull/19

2023-12-04 17:46 UTC, jimtronchet requested changes

2023-12-04 17:46 UTC, jimtronchet commented on lib/Calendar/calendar.dart
> +    final String url = 'https://localhost:7059/Calendar/matrozen';
Waarom default naar matrozen>?

2023-12-04 17:46 UTC, jimtronchet commented on lib/Calendar/calendar.dart
> +                          TextFormField(
Zet hier de value naar het event ipv de hinttext

2023-12-04 17:46 UTC, jimtronchet commented on lib/Calendar/calendar.dart
> +                          TextFormField(
DRY! dit hele formulier maak je nu 2x met enkele andere waardes, dit kan slimmer

2023-12-04 18:45 UTC, Vinciepincie commented
zat nog een bug in de formatting bij het editen van de date , ook bij create. Dit werkt nu ook

2023-12-18 18:55 UTC, TimGrootscholten approved these changes

2023-12-18 19:06 UTC, jimtronchet requested changes

2023-12-18 19:06 UTC, jimtronchet commented on lib/Calendar/calendar.dart
> +  TextEditingController enddateinput = TextEditingController();
Camel case please

2023-12-18 19:06 UTC, jimtronchet commented on lib/Calendar/calendar.dart
> +        // final Event appointmentDetails = details.appointments![0];
Remove this

2023-12-18 19:11 UTC, jimtronchet approved these changes

2023-12-18 19:11 UTC, merged