Feat/team b/login
ProjectMaasgroep18/ms18-flutter-applicatie pull request #27
Opened 2023-12-11 16:53 UTC by UDefine1

2023-12-11 17:01 UTC, jimtronchet requested changes
Ik heb wat kleine feedback punten op sommige benamingen, verder ziet het er wel mooi uit.

2023-12-11 20:13 UTC, jimtronchet requested changes
Loop alsjeblieft nog mijn feedback door.

2023-12-12 17:22 UTC, Chris3007 requested changes

2023-12-12 17:22 UTC, Chris3007 commented on lib/les/les.dart
Wil je deze er nog uithalen?

2023-12-12 17:22 UTC, Chris3007 commented on lib/menu.dart
> +import 'package:ms18_applicatie/les/les.dart';
En deze verwijzing naar les ook eruit halen?

2023-12-12 17:22 UTC, Chris3007 commented on lib/menu.dart
> +    menuItem.MenuItem(
En het menu voor les eruit halen

2023-12-12 19:44 UTC, Chris3007 commented
@UDefine1, het login scherm ziet er nu ook niet goed uit. ![screenshot](https://www.rspn.io/media/95AE22FC-3249-4583-86C7-D2241648E539.png)

2023-12-18 19:35 UTC, merged