Feat/team a/implement syncfusion calendar api
ProjectMaasgroep18/ms18-flutter-applicatie pull request #4
Opened 2023-10-23 16:49 UTC by TimGrootscholten

2023-10-23 16:54 UTC, jimtronchet requested changes

2023-10-23 16:54 UTC, jimtronchet commented on lib/Calendar/calendar.dart
> +              Colors.blue, // Vervang dit door de juiste achtergrondkleur
Moet je dit niet fixen?

2023-11-13 18:22 UTC, jimtronchet approved these changes

2023-11-13 18:23 UTC, Vinciepincie approved these changes

2023-11-13 18:23 UTC, merged